service: pr-check
plugins:
  - serverless-ruby-package

provider:
  name: aws
  runtime: ruby2.5
  stage: ${opt:stage, "development"}
  profile: se-dev

  stackTags:
    Env: ${self:provider.stage}
    App: ${self:service}

  environment:
    PRAPPROVED_TABLE_NAME: ${self:service}-${self:provider.stage}-PullRequestApprovals
    MENTIONS_TABLE_NAME: ${self:service}-${self:provider.stage}-PullRequestMentions
    MENTIONS_TTL: 2592000 # 30 days
    SLACK_TOKEN: ${env:SLACK_TOKEN}

  iamRoleStatements:
    # Give our lambda permission to store events in the mentions dynamodb table
    - Sid: MentionsReadWriteAccess
      Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:PutItem
      Resource:
         "Fn::GetAtt": [ PullRequestMentionsTable, Arn ]
    # Give our lambda permission to store events in the approvals dynamodb table
    - Sid: ApprovalsReadWriteAccess
      Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:PutItem
      Resource:
         "Fn::GetAtt": [ PullRequestApprovalsTable, Arn ]

package:
  include:
    - handlers.rb
    - lib/**

functions:
  slack:
    handler: handlers.Handlers.slack_event_received
    events:
      - http: POST /slack
  github:
    handler: handlers.Handlers.github_event_received
    events:
      - http: POST /github
  mark:
    handler: handlers.Handlers.mark_pr_approved
    events:
      # This endpoint is only used to ease manual invocation
      - http: POST /mark_prs
    environment:
      MARK_REACTION: white_check_mark
  # this is temporary, to get slack post mechanics working
  react:
    handler: handlers.Handlers.test_reaction
    events:
      - http: POST /reaction

resources:
  - Resources:
      #The DynamoDB table where we keep track of PRs that have been approved
      PullRequestApprovalsTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: ${self:service}-${self:provider.stage}-PullRequestApprovals
          AttributeDefinitions:
            - AttributeName: pr_id
              AttributeType: S
          KeySchema:
            - AttributeName: pr_id
              KeyType: HASH
          BillingMode: PAY_PER_REQUEST
      #The DynamoDB table where we keep track of Slack messages that mention PRs
      PullRequestMentionsTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: ${self:service}-${self:provider.stage}-PullRequestMentions
          AttributeDefinitions:
            - AttributeName: pr_id
              AttributeType: S
            - AttributeName: mention_id
              AttributeType: S
          KeySchema:
            - AttributeName: pr_id
              KeyType: HASH
            - AttributeName: mention_id
              KeyType: RANGE
          BillingMode: PAY_PER_REQUEST
          TimeToLiveSpecification:
            AttributeName: expires_at
            Enabled: true
