service: pr-check
plugins:
  - serverless-ruby-package

provider:
  name: aws
  runtime: ruby2.5
  stage: ${opt:stage, "development"}
  profile: se-dev

package:
  include:
    - handlers.rb
    - lib/**

functions:
  slack:
    handler: handlers.Handlers.slack_event_received
    events:
      - http: POST /slack
